apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: sample-apps
  sources:
    - repoURL: https://github.com/ccl-labs/platform-charts.git
      targetRevision: main
      path: charts/sample-frontend
      helm:
        valueFiles:
          - $values/apps/sample-frontend/values.yaml
    - repoURL: https://github.com/ccl-labs/platform-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ccl-labs/platform-gitops.git
      targetRevision: main
      path: apps/sample-frontend/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        # Gateway API が parentRefs にデフォルト補完するフィールドを無視
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
