apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: user-apps
  sources:
    - repoURL: https://github.com/ccl-labs/platform-charts.git
      targetRevision: main
      path: charts/generic-frontend
      helm:
        valueFiles:
          - $values/apps/test-app-frontend/values.yaml
    - repoURL: https://github.com/ccl-labs/platform-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ccl-labs/platform-gitops.git
      targetRevision: main
      path: apps/test-app-frontend/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
