apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-backup-secret
  namespace: sample-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: minio-backup-secret
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: minio-backup-secret-source
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: minio-backup-secret-source
        property: ACCESS_SECRET_KEY
