app:
  name: test-app-backend
image:
  repository: ghcr.io/ccl-labs/test-app-backend
  tag: latest
  pullSecretName: ghcr-pull-secret
containerPort: 8000
db:
  enabled: true
  name: test-app-db
  instances: 1
  postgresVersion: 17
  storageSize: 1Gi
